### ISSUE TITLE
Error "src/raven/terminal/functions.go"

### ISSUE THREAD

**Issue by piotrharry** [0x09AL/raven#25] opened 2018-10-03 15:38 UTC
hi 0x09AL,
I got this error while trying to do a "go build" for raven.

# raven/terminal
..\src\raven\terminal\functions.go:94:23: cannot use Scan (type "raven-go/model".Scan) as type "raven/model".Scan in argument to database.InsertScan
..\src\raven\terminal\functions.go:95:23: cannot use Scan (type "raven-go/model".Scan) as type "raven/model".Scan in argument to scraper.ExecuteScan
..\src\raven\terminal\functions.go:139:25: cannot use export (type "raven-go/model".Export) as type "raven/model".Export in argument to exporter.HandleExport
..\src\raven\terminal\functions.go:141:25: cannot use export (type "raven-go/model".Export) as type "raven/model".Export in argument to exporter.HandleExport

Do you have any ideas ? 
Thank you for your time

**Comment by 0x09AL** [comment] 2018-10-03 18:43
Hey @piotrharry ,
Seems I didn't change the program name on the terminal files.
As a workaround change from raven-go to raven.
Let me know if that works.

**Comment by piotrharry** [comment] 2018-10-04 08:50
Hi @0x09AL ,
First thank you for your fast reply.
The compilation worked fine. But I have another problem in the application. I configure a new scan with the name, the company and the domain. it works fine. But after that, this is impossible to access the export instance. I tried "use (scan_name)" with a lot of possible combination and nothing works. And before that, the scan was surprisingly fast. Do you have any ideas ? 
Thank you

**Comment by piotrharry** [comment] 2018-10-04 10:02
Hi @DocKali 
I found the answer to our question. You have to quit raven(scan) and get back to raven(main) to be able to do a "use (scan_name)".

**Comment by 0x09AL** [comment] 2018-10-04 11:19
@piotrharry you are correct. A scan is in the scan instance so you need to go **back** to use a scan.

Since the issue is solved, I'm closing this ! Please feel free to report anything that doesn't work.

Thanks

**Comment by DocKali** [comment] 2018-10-04 11:19
Excellent, thanks for the tip @piotrharry , I solve the problem!

@0x09AL, maybe you might include this in the readme?

**Closed by 0x09AL** 2018-10-04 11:19 UTC

**Comment by DocKali** [comment] 2018-10-04 12:36
Thanks for your quick reply !
